---
kind: pipeline
type: docker
name: bookdown-sdf

steps:
- name: build_test_image
  image: plugins/docker
  settings:
    username:
      from_secret: canister_username
    password:
      from_secret: canister_password
    repo: docker.io/chazu/bookdown-sdf
